export const WINDOW_IS_FOCUSED_CHANGED = 'WINDOW_FOCUSED';
export const WINDOW_GET_ID = 'WINDOW_GET_ID';
export const WINDOW_GET_IS_FOCUSED = 'WINDOW_GET_IS_FOCUSED';
export const WINDOW_GET_STATUS = 'WINDOW_GET_STATUS';
export const WINDOW_MAXIMIZE = 'WINDOW_MAXIMIZE';
export const WINDOW_MINIMIZE = 'WINDOW_MINIMIZE';
export const WINDOW_STATUS_CHANGED = 'WINDOW_STATUS_CHANGED';
export const WINDOW_UNMAXIMIZE = 'WINDOW_UNMAXIMIZE';
